name: Java CI

on:
  push:
    tags:
      - release.**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: gradleWrapper
      - name: Publish with Gradle
        run: |
          chmod +x gradlew
          ./gradlew publishSnapshotPublicationToSnapshotRepository \
          -PmavenUsername=${{ secrets.M2_USERNAME }} \
          -PmavenPassword=${{ secrets.M2_PASSWORD}} \
          -PpublicationVersion=${GITHUB_REF##*#}